import { ComponentProps } from './types'

export const ComponentDetails: ComponentProps[] = [
  {
    title: 'Badge',
    content: 'Used for text abbreviations or pillboxes.',
    story_url: 'badge',
    progress: 'completed',
    dev: 'Dan',
  },
  {
    title: 'Button',
    content: 'Used for click actions.',
    story_url: 'button',
    progress: 'completed',
    dev: 'Dan',
  },
  {
    title: 'Card',
    content: 'Used as a container to showcase smaller contents.',
    story_url: 'card',
    progress: 'completed',
    dev: 'Dan',
  },
  {
    title: 'Collapsible',
    content: 'Lorem ipsum dolor.',
    story_url: 'menu',
    progress: 'completed',
    dev: 'Eugene',
  },
  {
    title: 'Container',
    content: 'Lorem ipsum dolor.',
    story_url: 'container',
    progress: 'completed',
    dev: 'Eugene',
  },
  {
    title: 'Dropdown',
    content: 'Lorem ipsum dolor.',
    story_url: 'select',
    progress: 'inprogress',
    dev: 'Dan',
  },
  {
    title: 'Footer',
    content: 'Lorem ipsum dolor.',
    story_url: 'footer',
    progress: 'pending',
  },
  {
    title: 'Forms',
    content: 'Lorem ipsum dolor.',
    story_url: 'forms',
    progress: 'completed',
    dev: 'Eugene',
  },
  {
    title: 'Header',
    content: 'Lorem ipsum dolor.',
    story_url: 'header',
    progress: 'pending',
  },
  {
    title: 'Icon',
    content: 'Lorem ipsum dolor.',
    story_url: 'icon',
    progress: 'completed',
    dev: 'Dan',
  },
  {
    title: 'Image',
    content: 'Lorem ipsum dolor.',
    story_url: 'image',
    progress: 'completed',
    dev: 'Dan',
  },
  {
    title: 'Input',
    content: 'Lorem ipsum dolor.',
    story_url: 'input',
    progress: 'completed',
    dev: 'Eugene',
  },
  {
    title: 'Loader',
    content: 'Lorem ipsum dolor.',
    story_url: 'loader',
    progress: 'completed',
    dev: 'Dan',
  },
  {
    title: 'Login',
    content: 'Lorem ipsum dolor.',
    story_url: 'login',
    progress: 'completed',
    dev: 'Eugene',
  },
  {
    title: 'Logo',
    content: 'Lorem ipsum dolor.',
    story_url: 'logo',
    progress: 'completed',
    dev: 'Dan',
  },
  {
    title: 'Navigation',
    content: 'Lorem ipsum dolor.',
    story_url: 'navigation',
    progress: 'completed',
    dev: 'Eugene',
  },
  {
    title: 'Pagination',
    content: 'Lorem ipsum dolor.',
    story_url: 'pagination',
    progress: 'pending',
  },
  {
    title: 'Progress',
    content: 'Lorem ipsum dolor.',
    story_url: 'progress',
    progress: 'completed',
    dev: 'Dan',
  },
  {
    title: 'React Flow',
    content: 'Lorem ipsum dolor.',
    story_url: 'react-flow',
    progress: 'pending',
  },
  {
    title: 'Search',
    content: 'Lorem ipsum dolor.',
    story_url: 'search',
    progress: 'inprogress',
    dev: 'Kenneth',
  },
  {
    title: 'Select',
    content: 'Lorem ipsum dolor.',
    story_url: 'select',
    progress: 'inprogress',
    dev: 'Dan',
  },
  {
    title: 'Table',
    content: 'Lorem ipsum dolor.',
    story_url: 'table',
    progress: 'inprogress',
    dev: 'Dan',
  },
  {
    title: 'Tooltip',
    content: 'Lorem ipsum dolor.',
    story_url: 'tooltip',
    progress: 'inprogress',
    dev: 'Dan',
  },
]
